<a href="https://colab.research.google.com/github/22f1000003/Machine-Learnig-Practice/blob/week-1-machine-learning-prctice/concatinate_and_plot_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.   List item
2.   List item


#**Concat** in Pandas
---

Concat is a function that is used to concatenate two or more Pandas objects along a particular axis. The primary objects that concat operates on are DataFrames and Series.

---

In [3]:
import pandas as pd

# Create two sample DataFrames
temp_data = pd.DataFrame({'Date': ['12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023', '16-02-2023'],
                    'TempMax': [24.3, 26.9, 23.4, 15.5, 16.1 ] })

rainfall_data = pd.DataFrame({'Date': ['12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023', '16-02-2023'],
                    'Rainfall': [0, 3.6, 3.6, 39.8, 2.8 ] })

In [4]:
temp_data

         Date  TempMax
0  12-02-2023     24.3
1  13-02-2023     26.9
2  14-02-2023     23.4
3  15-02-2023     15.5
4  16-02-2023     16.1

In [5]:
rainfall_data

         Date  Rainfall
0  12-02-2023       0.0
1  13-02-2023       3.6
2  14-02-2023       3.6
3  15-02-2023      39.8
4  16-02-2023       2.8

In [8]:

# Concatenate along rows (axis=0)
result_col = pd.concat([temp_data, rainfall_data])
print("\nConcatenate along rows:")
print(result_col)

Concatenate along rows:
         Date  TempMax  Rainfall
0  12-02-2023     24.3       NaN
1  13-02-2023     26.9       NaN
2  14-02-2023     23.4       NaN
3  15-02-2023     15.5       NaN
4  16-02-2023     16.1       NaN
0  12-02-2023      NaN       0.0
1  13-02-2023      NaN       3.6
2  14-02-2023      NaN       3.6
3  15-02-2023      NaN      39.8
4  16-02-2023      NaN       2.8

In [9]:
final_concat

         Date  TempMax  Rainfall
0  12-02-2023     24.3       NaN
1  13-02-2023     26.9       NaN
2  14-02-2023     23.4       NaN
3  15-02-2023     15.5       NaN
4  16-02-2023     16.1       NaN
0  12-02-2023      NaN       0.0
1  13-02-2023      NaN       3.6
2  14-02-2023      NaN       3.6
3  15-02-2023      NaN      39.8
4  16-02-2023      NaN       2.8

In [10]:
# concatinate along rows (axis=0)
final_concat = pd.concat([temp_data,rainfall_data],axis=1)

In [11]:

final_concat

         Date  TempMax        Date  Rainfall
0  12-02-2023     24.3  12-02-2023       0.0
1  13-02-2023     26.9  13-02-2023       3.6
2  14-02-2023     23.4  14-02-2023       3.6
3  15-02-2023     15.5  15-02-2023      39.8
4  16-02-2023     16.1  16-02-2023       2.8

In [12]:
final_concat_key1 = pd.concat([temp_data,rainfall_data] ,keys=['a','b'])

In [13]:
final_concat_key1

           Date  TempMax  Rainfall
a 0  12-02-2023     24.3       NaN
  1  13-02-2023     26.9       NaN
  2  14-02-2023     23.4       NaN
  3  15-02-2023     15.5       NaN
  4  16-02-2023     16.1       NaN
b 0  12-02-2023      NaN       0.0
  1  13-02-2023      NaN       3.6
  2  14-02-2023      NaN       3.6
  3  15-02-2023      NaN      39.8
  4  16-02-2023      NaN       2.8

In [15]:
final_concat_key1.loc['a']['TempMax'].max()

26.9

In [16]:
# Creating the first DataFrame
data1 = {'Name': ['Alice', 'Bob', 'Charlie'],
         'Age': [25, 30, 35],
         'Score': [85, 90, 88]}
df1 = pd.DataFrame(data1)

# Creating the second DataFrame
data2 = {'Name': ['David', 'Eve', 'Charlie'],
         'Age': [27, 32, 35],
         'Score': [82, 88, 88],
         "extra":[100,100,100]}
df2 = pd.DataFrame(data2)

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

DataFrame 1:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88

DataFrame 2:
      Name  Age  Score  extra
0    David   27     82    100
1      Eve   32     88    100
2  Charlie   35     88    100

In [17]:
df1

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88

In [18]:
df2

      Name  Age  Score  extra
0    David   27     82    100
1      Eve   32     88    100
2  Charlie   35     88    100

In [19]:
final_concat_key2 = pd.concat([df1,df2],axis=0,)

In [20]:
result_col_inner2 = pd.concat([df1, df2], axis=0, join='inner',ignore_index=True)
result_col_inner2

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88
3    David   27     82
4      Eve   32     88
5  Charlie   35     88

In [ ]:
final_concat_key2

         a                  b
      Name Age Score     Name Age Score extra
0    Alice  25    85    David  27    82   100
1      Bob  30    90      Eve  32    88   100
2  Charlie  35    88  Charlie  35    88   100

In [21]:
result_col_inner2_1 = pd.concat([df1, df2], axis=1,ignore_index=True)
result_col_inner2_1

         0   1   2        3   4   5    6
0    Alice  25  85    David  27  82  100
1      Bob  30  90      Eve  32  88  100
2  Charlie  35  88  Charlie  35  88  100

In [22]:
final_concat_key2['a']['Score'].min()

85

In [23]:
final_data = pd.concat([df1,df2],axis=0,join='inner')

In [24]:
final_data

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88
0    David   27     82
1      Eve   32     88
2  Charlie   35     88

## keys

In [25]:

result_col_key1 = pd.concat([temp_data, rainfall_data], axis=0, keys=('Delhi','Chennai'))
print("\nConcatenate along columns with keys, axis = 0:")
print(result_col_key1)

Concatenate along columns with keys, axis = 0:
                 Date  TempMax  Rainfall
Delhi   0  12-02-2023     24.3       NaN
        1  13-02-2023     26.9       NaN
        2  14-02-2023     23.4       NaN
        3  15-02-2023     15.5       NaN
        4  16-02-2023     16.1       NaN
Chennai 0  12-02-2023      NaN       0.0
        1  13-02-2023      NaN       3.6
        2  14-02-2023      NaN       3.6
        3  15-02-2023      NaN      39.8
        4  16-02-2023      NaN       2.8

In [28]:
result_col_key1.loc["Delhi"]['TempMax'][4]

np.float64(16.1)

In [29]:
max_temp_A = result_col_key1['A']['TempMax'].max()
print("Maximum temperature in section A:", max_temp_A)

KeyError: 'A'