<a href="https://colab.research.google.com/github/22f1000003/Machine-Learnig-Practice/blob/week-1-machine-learning-prctice/Merge_and_join_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

data1 = {
    "ID" : [10001,20002,30003,40004,50005],
    "Numbers": [10,20,30,40,50],
    "Letters":["A","B","C","D","E"]
}

In [ ]:
df1 = pd.DataFrame(data1)

In [ ]:
df1

      ID  Numbers Letters
0  10001       10       A
1  20002       20       B
2  30003       30       C
3  40004       40       D
4  50005       50       E

In [ ]:
data2 = {
    "ID" : [10001,20002,30003,60006,70007],
    "Numbers": [10,20,30,40,60],
    "City":["Lucknow","Munnar","Chennai","Delhi","Jaipur"]
}

In [ ]:
df2 = pd.DataFrame(data2)

In [ ]:
df2

      ID  Numbers     City
0  10001       10  Lucknow
1  20002       20   Munnar
2  30003       30  Chennai
3  60006       40    Delhi
4  70007       60   Jaipur

In [ ]:
merge_data = df1.merge(df2,how='inner')

In [ ]:
merge_data

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai

In [ ]:
merge_data = df1.merge(df2,how='inner',on='ID')

In [ ]:
merge_data

      ID  Numbers_x Letters  Numbers_y     City
0  10001         10       A         10  Lucknow
1  20002         20       B         20   Munnar
2  30003         30       C         30  Chennai

In [ ]:
merge_data = df1.merge(df2,how='inner',on=['ID','Numbers'])

In [ ]:
merge_data

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai

In [ ]:
merge_data = df1.merge(df2,how='outer')

In [ ]:
merge_data

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai
3  40004       40       D      NaN
4  50005       50       E      NaN
5  60006       40     NaN    Delhi
6  70007       60     NaN   Jaipur

In [ ]:
merge_data = df1.merge(df2,how='outer', on='ID')

In [ ]:
merge_data

      ID  Numbers_x Letters  Numbers_y     City
0  10001       10.0       A       10.0  Lucknow
1  20002       20.0       B       20.0   Munnar
2  30003       30.0       C       30.0  Chennai
3  40004       40.0       D        NaN      NaN
4  50005       50.0       E        NaN      NaN
5  60006        NaN     NaN       40.0    Delhi
6  70007        NaN     NaN       60.0   Jaipur

In [ ]:
merge_data = df1.merge(df2,how='outer', on=['ID','Numbers'])

In [ ]:
merge_data

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai
3  40004       40       D      NaN
4  50005       50       E      NaN
5  60006       40     NaN    Delhi
6  70007       60     NaN   Jaipur

In [ ]:
merge_data3 = df1.merge(df2,how='outer')

In [ ]:
merge_data3

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai
3  40004       40       D      NaN
4  50005       50       E      NaN
5  60006       40     NaN    Delhi
6  70007       60     NaN   Jaipur

In [ ]:
merge_data3 = df1.merge(df2,how='outer', on='ID')
merge_data3

      ID  Numbers_x Letters  Numbers_y     City
0  10001       10.0       A       10.0  Lucknow
1  20002       20.0       B       20.0   Munnar
2  30003       30.0       C       30.0  Chennai
3  40004       40.0       D        NaN      NaN
4  50005       50.0       E        NaN      NaN
5  60006        NaN     NaN       40.0    Delhi
6  70007        NaN     NaN       60.0   Jaipur

In [ ]:
merge_data3 = df1.merge(df2,how='left')
merge_data3

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai
3  40004       40       D      NaN
4  50005       50       E      NaN

In [ ]:
merge_data3 = df1.merge(df2,how='right')
merge_data3

      ID  Numbers Letters     City
0  10001       10       A  Lucknow
1  20002       20       B   Munnar
2  30003       30       C  Chennai
3  60006       40     NaN    Delhi
4  70007       60     NaN   Jaipur

In [ ]:
cross_merge = df1.merge(df2,how='cross')
cross_merge

     ID_x  Numbers_x Letters   ID_y  Numbers_y     City
0   10001         10       A  10001         10  Lucknow
1   10001         10       A  20002         20   Munnar
2   10001         10       A  30003         30  Chennai
3   10001         10       A  60006         40    Delhi
4   10001         10       A  70007         60   Jaipur
5   20002         20       B  10001         10  Lucknow
6   20002         20       B  20002         20   Munnar
7   20002         20       B  30003         30  Chennai
8   20002         20       B  60006         40    Delhi
9   20002         20       B  70007         60   Jaipur
10  30003         30       C  10001         10  Lucknow
11  30003         30       C  20002         20   Munnar
12  30003         30       C  30003         30  Chennai
13  30003         30       C  60006         40    Delhi
14  30003         30       C  70007         60   Jaipur
15  40004         40       D  10001         10  Lucknow
16  40004         40       D  20002         20   Munnar
17  40004         40       D  30003         30  Chennai
18  40004         40       D  60006         40    Delhi
19  40004         40       D  70007         60   Jaipur
20  50005         50       E  10001         10  Lucknow
21  50005         50       E  20002         20   Munnar
22  50005         50       E  30003         30  Chennai
23  50005         50       E  60006         40    Delhi
24  50005         50       E  70007         60   Jaipur